---
- name: Local Test Rules
  hosts: all
  sources:
    - name: Generate a range
      benthomasson.eda.range:
        limit: 2000
  rules:
    - name: print event 200
      condition: event.i == 200
      action:
        print_event:

    - name: 
      condition: event.i == 400
      action:
        assert_fact:
          fact:
            fact_matched: "400 matched"

    - name:
      condition: event.fact_matched == "400 matched"
      action:
        run_playbook:
          name: print.yml


    - name: run print playbook
      condition: event.i == 300
      action:
        run_playbook:
          name: print.yml
